name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install
        run: |
          # Use npm ci when a lockfile exists for deterministic installs,
          # otherwise fall back to npm install so CI doesn't fail on repos
          # without a committed lockfile.
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test
      - name: Build
        run: npm run build
